# Generated by Django 4.1.7 on 2023-03-18 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('instructions', models.TextField()),
                ('prep_time', models.PositiveIntegerField()),
                ('cook_time', models.PositiveIntegerField()),
                ('servings', models.PositiveIntegerField()),
            ],
        ),
    ]
